# ref. https://goreleaser.com/customization/build/
version: 2

builds:
  - id: eigenlayer-cli
    main: ./cmd/eigenlayer/main.go
    binary: eigenlayer
    flags:
      - -v
    ldflags:
      - -X 'main.version={{.Version}}'
      - -X 'github.com/Layr-Labs/eigenlayer-cli/pkg/telemetry.telemetryToken={{ .Env.TELEMETRY_TOKEN }}'
      - -X 'github.com/Layr-Labs/eigenlayer-cli/pkg/telemetry.version={{.Version}}'
      - -X 'github.com/Layr-Labs/eigenlayer-cli/pkg/rewards.preprodUrl={{.Env.EIGENLAYER_BACKEND_PREPROD_URL}}'
      - -X 'github.com/Layr-Labs/eigenlayer-cli/pkg/rewards.mainnetUrl={{.Env.EIGENLAYER_BACKEND_MAINNET_URL}}'
      - -X 'github.com/Layr-Labs/eigenlayer-cli/pkg/rewards.testnetUrl={{.Env.EIGENLAYER_BACKEND_TESTNET_URL}}'
    # windows is ignored by default, as the `goos` field by default only
    # contains linux and darwin
    env:
        - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: layr-labs
    name: eigenlayer-cli

  draft: true