name: Check make fmt
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  check-make-fmt:
    name: Check make fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: install go1.21
        uses: actions/setup-go@0a12ed9d6a96ab950c2f4c6b1299c0cb65ebd369 # v5.2.0
        with:
          go-version: "1.21"

      - name: Run make fmt
        run: make fmt

      - name: Check if make fmt generated changes that should be committed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: make fmt generated changes that should be committed. Please run 'make fmt' and commit the changes."
            git diff
            git status
            exit 1
          fi