name: lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@0a12ed9d6a96ab950c2f4c6b1299c0cb65ebd369 # v5.2.0
        with:
          go-version: '1.21'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 # v6.1.1
        with:
          version: latest
          args: --timeout 3m