name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Unit Test
        run: make tests